from __future__ import annotations

import argparse
from pathlib import Path

from ingest.registry import load_registry

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY_PATH = REPO_ROOT / "ingest" / "registry.yaml"
DEFAULT_OUTPUT_PATH = REPO_ROOT / "web" / "src" / "registry.generated.ts"


def render_indicator_keys(registry_path: Path) -> str:
    keys = [entry.key for entry in load_registry(registry_path).root]
    quoted_keys = ",\n".join(f'  "{key}"' for key in keys)
    return (
        "// Generated by scripts/generate_indicator_keys.py; do not edit by hand.\n"
        "export const INDICATOR_KEYS = [\n"
        f"{quoted_keys}\n"
        "] as const;\n\n"
        "export type IndicatorKey = (typeof INDICATOR_KEYS)[number];\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the frontend literal indicator-key union."
    )
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    args = parser.parse_args()

    args.output.write_text(
        render_indicator_keys(args.registry),
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
