create type public.datapoint_status as enum (
  'OK',
  'STALE',
  'UNAVAILABLE',
  'ERROR'
);

create type public.unavailable_reason as enum (
  'NOT_DEFINABLE',
  'PAYWALLED',
  'FETCH_FAILED',
  'NOT_FETCHED'
);

create table public.datapoints (
  id bigint generated by default as identity primary key,
  indicator_key text not null,
  asset text not null,
  measured_on text not null,
  value double precision,
  status public.datapoint_status not null,
  reason public.unavailable_reason,
  source_vendor text not null,
  endpoint text not null,
  source_field text not null,
  fetched_at timestamptz not null,
  source_timestamp timestamptz,
  constraint asset_match
    check (status <> 'OK' or measured_on = asset),
  constraint value_iff_ok
    check ((status in ('OK', 'STALE')) = (value is not null)),
  constraint reason_required
    check ((status in ('UNAVAILABLE', 'ERROR')) = (reason is not null))
);

create index datapoints_indicator_asset_fetched_at_idx
  on public.datapoints (indicator_key, asset, fetched_at desc);

alter table public.datapoints enable row level security;

create policy datapoints_select_only
  on public.datapoints
  for select
  to anon, authenticated
  using (true);

revoke all on public.datapoints from anon, authenticated;
grant select on public.datapoints to anon, authenticated;

create view public.datapoints_read
with (security_invoker = true)
as
select
  id,
  indicator_key,
  asset,
  measured_on,
  value,
  status,
  reason,
  source_vendor,
  endpoint,
  source_field,
  fetched_at,
  source_timestamp
from public.datapoints;

revoke all on public.datapoints_read from anon, authenticated;
grant select on public.datapoints_read to anon, authenticated;
