create type public.corroboration_status as enum (
  'CORROBORATED',
  'DIVERGED',
  'NOT_CORROBORATED',
  'UNCORROBORATED'
);

create unique index datapoints_venue_identity_idx
  on public.datapoints (
    indicator_key,
    asset,
    source_vendor,
    source_timestamp
  ) nulls not distinct;

create table public.corroborations (
  id bigint generated by default as identity primary key,
  datapoint_a_id bigint not null
    references public.datapoints (id) on delete cascade,
  datapoint_b_id bigint
    references public.datapoints (id) on delete cascade,
  divergence_bps double precision,
  tolerance_bps_at_write double precision,
  status public.corroboration_status not null,
  reason text,
  constraint different_datapoints
    check (datapoint_b_id is null or datapoint_a_id < datapoint_b_id),
  constraint comparison_values_together
    check (
      (datapoint_b_id is not null
        and divergence_bps is not null
        and tolerance_bps_at_write is not null
        and reason is null)
      or
      (datapoint_b_id is null
        and divergence_bps is null
        and tolerance_bps_at_write is null
        and reason is not null)
    ),
  constraint nonnegative_divergence
    check (divergence_bps is null or divergence_bps >= 0),
  constraint nonnegative_tolerance
    check (tolerance_bps_at_write is null or tolerance_bps_at_write >= 0)
);

create unique index corroborations_datapoint_pair_idx
  on public.corroborations (datapoint_a_id, datapoint_b_id) nulls not distinct;

alter table public.corroborations enable row level security;

create policy corroborations_select_only
  on public.corroborations
  for select
  to anon, authenticated
  using (true);

revoke all on public.corroborations from anon, authenticated;
grant select on public.corroborations to anon, authenticated;

create view public.corroborations_read
with (security_invoker = true)
as
select
  id,
  datapoint_a_id,
  datapoint_b_id,
  divergence_bps,
  tolerance_bps_at_write,
  status,
  reason
from public.corroborations;

revoke all on public.corroborations_read from anon, authenticated;
grant select on public.corroborations_read to anon, authenticated;
